environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build
  - npm install --global . --no-optional

test_script:
  - node --version
  - npm --version
  - npm test

cache:
 - node_modules
 - '%APPDATA%\npm-cache'

build: off
