language: node_js
node_js:
  - node
  - 8
env:
  - PKG_ENV=npm
  - PKG_ENV=yarn
before_install:
  - if [[ "$PKG_ENV" == "yarn" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [[ "$PKG_ENV" == "yarn" ]]; then export PATH=$HOME/.yarn/bin:$PATH; fi
before_script:
  - npm install --global . --no-optional
os:
  - linux
  - osx
addons:
  firefox: latest
  chrome: stable
