version: 2
jobs:
  node8_npm:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm build
      - run: npm install --global .
      - run: npm run test
  node9_npm:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew upgrade npm
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm build
      - run: npm install --global .
      - run: npm run test
  node8_yarn:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn
  node9_yarn:
    macos:
      xcode: "9.1.0"
    steps:
      - checkout
      - run: brew upgrade yarn
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn

workflows:
  version: 2
  build:
    jobs:
      - node8_npm
      - node9_npm
      - node8_yarn
      - node9_yarn
