version: 2

jobs:
  node8_npm:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm build
      - run: npm install --global .
      - run: npm run test
  node10_npm:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew upgrade npm
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm build
      - run: npm install --global .
      - run: npm run test
  node8_yarn:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: yarn --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn
  node10_yarn:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew upgrade yarn || true
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: yarn --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn run build
      - run: yarn global add file:$PWD
      - run: yarn run pretest
      - run: yarn run test:yarn

workflows:
  version: 2
  build:
    jobs:
      - node8_npm
      - node10_npm
      - node8_yarn
      - node10_yarn
