version: 2

jobs:
  node8:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm install --global packages/cli
      - run: npm test
  node10:
    macos:
      xcode: "9.4.0"
    steps:
      - checkout
      - run: brew upgrade npm
      - run: brew install caskroom/cask/firefox caskroom/cask/google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm install --global packages/cli
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - node8
      - node10
